# params.yaml  (nur der ML-Teil)
Pipeline:
  - PCA
  - VotingClassifier          # Reihenfolge ⇒ erst PCA, dann Ensemble

Models:                       #   Abschnittsüberschrift
  PCA:
    type: sklearn.decomposition.PCA
    init_args:
      n_components: 30        # wird vom advanced-Skript überschrieben

  LinearDiscriminantAnalysis:
    type: sklearn.discriminant_analysis.LinearDiscriminantAnalysis
    init_args:
      solver: svd

  RandomForestClassifier:
    type: sklearn.ensemble.RandomForestClassifier
    init_args:
      n_estimators: 500
      max_leaf_nodes: 2
      random_state: 6020

  SVC:
    type: sklearn.svm.SVC
    init_args:
      kernel: linear
      probability: true
      random_state: 6020

  VotingClassifier:           # **nach** den Basismodellen!
    type: sklearn.ensemble.VotingClassifier
    init_args:
      flatten_transform: false
    estimators:
      - LinearDiscriminantAnalysis
      - RandomForestClassifier
      - SVC